version: '3.5'

services:
  app:
    build: 
      context: ./challenge-api
      dockerfile: dockerfile
    container_name: challenge-api
    environment:
      - PORT=$[PORT]
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src